spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blueseaplus
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      password: root
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
  mail:
    host: smtp.qq.com
    username: 2567407595@qq.com
    password: jwfteykhexkpebbg
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081
  servlet:
    context-path: /

image:
  storage:
    directory: G:/毕业设计/Blue - Ocean Technology(H5)/public/chats